sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.3


matrix:
  include:
    - php: 7.3
      env: SYMFONY_VERSION=5.0
  fast_finish: true

before_install:
  - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then phpenv config-rm xdebug.ini; fi
  - if [[ "$SYMFONY_VERSION" != "" ]]; then composer require --dev symfony/symfony:$SYMFONY_VERSION; fi
  - if [[ "$TRAVIS_VERSION" != "" ]]; then composer require --dev twig/twig:$TWIG_VERSION; fi

install:
  - composer install --prefer-dist